# Generated by Django 3.2.4 on 2022-10-15 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('deadline_date', models.DateField()),
                ('deadline_time', models.TimeField(blank=True, null=True)),
                ('finished_on_date', models.DateField(blank=True, null=True)),
                ('finished_on_time', models.TimeField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
        ),
    ]
