# Generated by Django 3.2.4 on 2022-10-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=100)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Not Started', max_length=30)),
                ('priority', models.CharField(default='Low', max_length=30)),
            ],
        ),
    ]
